---
name: Data-FormValidator-EmailValid
version: 0.02
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: Data::FormValidator e-mail address constraint/filter
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::FormValidator: 4
  Email::Valid: 0
recommends:
  Net::DNS: 0
provides:
  Data::FormValidator::EmailValid:
    file: lib/Data/FormValidator/EmailValid.pm
    version: 0.02
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
